# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Personal website of Martin Lainer
email: mlainer@arcor.de
description: "Researcher in atmospheric sciences"
  
domain: mlainer.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mlainer.github.io" # the base hostname & protocol for your site, e.g. 
author:
  name: "Martin Lainer"
  avatar: "/assets/images/profile_picture.jpg" # Replace with your profile image
  bio: "I am a meteorologist and physicist with deep expertise in weather radar technology, atmospheric data analysis, and algorithm development. With a proven track record in research and applied projects, including work on weather radar systems, drones, wind profiling, and data processing, I have significantly contributed to research projects and operational efficiency. Driven by a passion for scientific discovery, I am combining advanced technical skills with a focus on practical solutions, particularly in the fields of the atmospheric sciences."
  location: "Locarno, Switzerland"
  links:
    - label: "Google Scholar"
      icon: "google-scholar"
      url: "https://scholar.google.com/citations?user=Mx84gAUAAAAJ&hl=de"
    - label: "ORCID"
      icon: "orcid"
      url: "https://orcid.org/0000-0002-1129-3406"
    - label: "LinkedIn"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/mlainer/"


github_username:  mlainer

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-optional-front-matter

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        nav: "docs"  # Create a custom navigation file in `_data/navigation.yml`

google_analytics: G-W7WWVCFZGE # Replace with your tracking ID

# SEO settings
seo:
  title: "Martin Lainer - Researcher in atmospheric sciences"
  description: "Scientific collaborator at MeteoSwiss, focusing on radar meteorology."

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
