title: Personal website of Martin Lainer
email: mlainer@arcor.de
description: "Researcher in atmospheric sciences"
author_profile: true  
domain: mlainer.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mlainer.github.io" # the base hostname & protocol for your site, e.g. 

author:
  name: "Martin Lainer"
  avatar: "/assets/images/profile_picture.jpg" # Replace with your profile image
  bio: "I am a meteorologist and physicist with deep expertise in weather radar technology, atmospheric data analysis, and algorithm development. With a proven track record in research and applied projects, including work on weather radar systems, drones, wind profiling, and data processing, I have significantly contributed to research projects and operational efficiency. Driven by a passion for scientific discovery, I am combining advanced technical skills with a focus on practical solutions, particularly in the fields of the atmospheric sciences."
  location: "Locarno, Switzerland"
  links:
    - label: "Google Scholar"
      icon: "google-scholar"
      url: "https://scholar.google.com/citations?user=Mx84gAUAAAAJ&hl=de"
    - label: "ORCID"
      icon: "orcid"
      url: "https://orcid.org/0000-0002-1129-3406"
    - label: "LinkedIn"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/mlainer/"


github_username:  mlainer
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-optional-front-matter

markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - autolink
    - fenced_code_blocks
    - strikethrough
    - lax_spacing
    - space_after_headers
    - with_toc_data

google_analytics: G-W7WWVCFZGE # Replace with your tracking ID

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        nav: "docs"  # Create a custom navigation file in `_data/navigation.yml`

# SEO settings
seo:
  title: "Martin Lainer - Researcher in atmospheric sciences"
  description: "Scientific collaborator at MeteoSwiss, focusing on radar meteorology."
